### ISSUE TITLE
Error while running migration

### ISSUE THREAD

**Issue by FMpoli** [tomatophp/filament-plugins#10]
After build my plugin with the GUI
I try to run a migration and I get

mkdir(): No such file or directory

after debug, I've found 

"/var/www/html/Modules/Wharehouse/Database/migrations/" // vendor/tomatophp/filament-plugins/src/Services/Concerns/GenerateMigrations.php:18

I'm on MacOsx with Colima + Dev environment

**Comment by fadymondy** [comment]
fixed

**Comment by FMpoli** [comment]
Thanks, i will try tonight
