### ISSUE TITLE
After I define a route in the api.php of the plugin, I can't find the route in route:list.

### ISSUE THREAD

**Issue by shebaoting** [tomatophp/filament-plugins#11]
After I define a route in the api.php of the plugin, I can't find the route in route:list.

Modules/AuthorisationCentre/routes/api.php
```
Route::get('/user/111', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');

```

Then I run the following command
```
php artisan route:list
```
I can't find this route

**Comment by fadymondy** [comment]
it's okay you just need to make sure that your plugin is active
