### ISSUE TITLE
Soft deletes not set

### ISSUE THREAD

**Issue by FMpoli** [tomatophp/filament-plugins#16]
Even if soft delete is selected for the table, in the database it remains at 0. I haven't been able to migrate yet due to another bug, but I believe it should be set to 1.

![Screenshot 2024-06-24 alle 19 54 16](https://github.com/tomatophp/filament-plugins/assets/107031416/4ace0a5a-da11-4abe-97d5-58ef86ea5d2a)

**Comment by fadymondy** [comment]
now you can set the soft_delete and timestamp when you create the table or on table update.
