### ISSUE TITLE
Unable to create model, resource, page etc.. 

### ISSUE THREAD

**Issue by FMpoli** [tomatophp/filament-plugins#17]
if i fix this bug with my solution https://github.com/tomatophp/filament-plugins/issues/15
i'm able to migrate (create the migration file by clicking on the database icon)
i suggest to change the tooltip from 'migrate' to 'create migration' to avoid misunderstanding with the 'Migrate' in the dropdown under 'generate'

after this, i launch the Migrate under Generate
and it works, the table is created on the db

then i create the model and it works 
```
<?php

namespace Modules\Warehouse\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * @property string $id
* @property string $name
* @property string $slug
* @property string $url
 */
class WarehouseBrand extends Model
{
    /**
     * @var array
     */
    protected $fillable = [
        'id',
        'name',
        'slug',
        'url'
    ];
}
```
but, when i try the other options, i get this message

The model could not be found generate it first.

**Comment by fadymondy** [comment]
i think it's a namespace problem i will check it
