### ISSUE TITLE
Error Plugin creator

### ISSUE THREAD

**Issue by slamservice** [tomatophp/filament-plugins#18]
I was creating a new plugin and I got the error:

Class "Modules\InformaCRM\Providers\InformaCRMServiceProvider" not found

C:\TuttoQui\laragon\laragon\www\biblioteca\public\index
.php
 
<?php
use Illuminate\Http\Request;
define('LARAVEL_START', microtime(true));
// Determine if the application is in maintenance mode...
if (file_exists($maintenance = __DIR__.'/../storage/framework/maintenance.php')) {
    require $maintenance;
}

// Register the Composer autoloader...
require __DIR__.'/../vendor/autoload.php';

// Bootstrap Laravel and handle the request...
(require_once __DIR__.'/../bootstrap/app.php')
    ->handleRequest(Request::capture());

**Comment by slamservice** [comment]
The problem is providers path:
Class "Modules\InformaCRM\Providers\InformaCRMServiceProvider" not found
Class "Modules\InformaCRM\**app\**Providers\InformaCRMServiceProvider"

**Comment by fadymondy** [comment]
you need to use

```bash
composer dump-autoload
```

and make sure you do all the steps like add Module to composer.json

```json
"extra": {
    "laravel": {
        "dont-discover": []
    },
    "merge-plugin": {
        "include": [
            "Modules/*/composer.json"
        ]
    }
},
```

**Comment by ashkesarmaa** [comment]
I'm having the same issue. I followed all the steps and checked them carefully multiple times.
