### ISSUE TITLE
Glitch in the UI while create migrations

### ISSUE THREAD

**Issue by FMpoli** [tomatophp/filament-plugins#19]
Now that i have 2 plugins in the works, i have found a bug
if you are in the plugin db table list, when you click on the db icon to create the migration, the table updates and  show all the db tables of all plugins. The migration is correctly generated.

When you try to migrate, same as above but with error because the plugin try to migrate a migration from the other plugin.

**Comment by fadymondy** [comment]
@FMpoli thanks for your report i will fix is ASAP.

**Comment by fadymondy** [comment]
fixed on the last version

**Comment by FMpoli** [comment]
Thanks!

**Comment by FMpoli** [comment]
With this update, i've lost all my tables definitions... is it possible to recover the past work or i need to start from scratch (again)?

**Comment by fadymondy** [comment]
@FMpoli how did you lose it?! the update doesn't delete or remove anything from the database.

**Comment by FMpoli** [comment]
ok, tables and tables_cols are empty in my db after the update...
i will make some test in these days

**Comment by fadymondy** [comment]
@FMpoli sorry for that, please let me know about any updates on this issue.

**Comment by jijesh-cherayi** [comment]
There is some issue with TomatoPHP plugins
```
QueryException for the tomatophp filament plugins
could not find driver (Connection: , SQL: create table "plugins" ("id" integer primary key autoincrement not null, "module_name" varchar, "title" text, "description" text, "color" varchar, "placeholder" varchar, "icon" varchar, "version" varchar, "docs" varchar, "github" varchar, "active" tinyint(1), "providers" text, "type" varchar))
```

Laravel 11.x
Mysql 8
Filament 3.x
PHP 8.3
Ubuntu System
