### ISSUE TITLE
trans() fields notificationss with double S throughout project

### ISSUE THREAD

**Issue by eelco2k** [tomatophp/filament-plugins#22]
on some places within this plugin there is a typo in the translations. The key "notificationss" should be "notifications" (single S)

one example:

```php
trans('filament-plugins::messages.plugins.notificationss.disabled.title')
```

should be:
```php
trans('filament-plugins::messages.plugins.notifications.disabled.title')
```

**Comment by fadymondy** [comment]
hi @eelco2k thanks for your report, we will update that ASAP to make sure that everything is correct.

**Comment by fadymondy** [comment]
fixed on last version.
