### ISSUE TITLE
Add Support for Multi Panel

### ISSUE THREAD

**Issue by CookieMC337** [tomatophp/filament-plugins#7]
It would be best if you could select which panel (e.g. app and admin) it should be for when creating a page/resource and only register it there. In my opinion, otherwise no plugin system makes sense if I can only use it on one level.

![image](https://github.com/tomatophp/filament-plugins/assets/51511368/cbbe8724-c1fd-496e-a0f4-30591ddd726d)

**Comment by fadymondy** [comment]
Okay, I get you.

from v1.0.6

## Use Selected Module in your panel

you can use the selected module in your panel by using this code in your PanelProvider

```php
->plugin(\TomatoPHP\FilamentPlugins\FilamentPluginsPlugin::make()->modules([
    'CRM'
]))
```

so you will see only the selected modules in your panel

## Stop Auto Discover Module Resources

you can stop auto-load module resources by using this code in your PanelProvider

```php
->plugin(\TomatoPHP\FilamentPlugins\FilamentPluginsPlugin::make()->autoDiscoverModules(false))
```

**Comment by fadymondy** [comment]
from v1.0.7

## Get Only Current Panel Plugins

on any plugin you can create a Page/Resource/Widget for the selected panel, so if you need to showup only the current panel Page/Resources/Widgets you can use this code in your PanelProvider

```php
->plugin(\TomatoPHP\FilamentPlugins\FilamentPluginsPlugin::make()->discoverCurrentPanelOnly())
```
