### ISSUE TITLE
Register resources/asstes folder to get Files

### ISSUE THREAD

**Issue by CookieMC337** [tomatophp/filament-plugins#8]
You already have the option of adding your own images. However, if I store a logo.svg in the assets folder and store it in the modul.json, for example, it is not rendered. 

Furthermore, if you insert the image as URL in the module.json there is no fixed size. Sometimes the logo disappears behind the card.

![image](https://github.com/tomatophp/filament-plugins/assets/51511368/74f8fb2e-60d8-41a6-8621-696cda6b4c90)
![image](https://github.com/tomatophp/filament-plugins/assets/51511368/66c7c1f9-d2d7-4dbd-be66-0953ecbd8c52)
![image](https://github.com/tomatophp/filament-plugins/assets/51511368/92b944ed-edee-4cab-b099-01571fa1876d)

**Comment by fadymondy** [comment]
thanks for your report, I will work on it to add a fixed box dev for the image and add an option to set the image from the internal link

**Comment by fadymondy** [comment]
@CookieMC337 what did you expect the image to be? change on size as an option?

**Comment by fadymondy** [comment]
okay you can use images from storage when you store them in `public` folder and you can access this image like `/images/logo.png`, for images, we recommend making it a cover image not just a logo without a background so you can add a background to your logo and then attach it.
