### ISSUE TITLE
Undefined property: stdClass::$zh_CN

### ISSUE THREAD

**Issue by shebaoting** [tomatophp/filament-plugins#9]
After I create the plugin, it prompts an error message
```
Undefined property: stdClass::$zh_CN
```
![image](https://github.com/tomatophp/filament-plugins/assets/29738814/83556f80-09c5-40dc-80a9-f01024660519)

**Comment by fadymondy** [comment]
that means your `module.json` doesn't have a title for `zh_CN` lang please add it
